const project = '/images/project_thumnails/'
const people = '/images/people/'

const projects = [
  {
    id: '1',
    url: 'https://manchester-city-46483.web.app/',
    image: `${project}manchester-city-logo.svg`,
    title: 'Man City',
    desc: 'A FERN stack homepage for the famous football club.',
  },
  {
    id: '2',
    url: 'https://www.liamgallagher.com/index.php',
    image: `${people}liam_gallagher.png`,
    title: 'Coming Soon',
    desc: 'In the meantime, peruse the britpop Titan himself...',
  },
  {
    id: '3',
    url: 'https://www.trsite.org/',
    image: `${people}teddy_roosevelt.png`,
    title: 'Coming Soon',
    desc: "In the meantime, peruse Babylon's most energetic Head of State.",
  },
  {
    id: '4',
    url: 'https://www.google.com',
    image: `${people}nikola_tesla.png`,
    title: 'Coming Soon',
    desc:
      "In the meantime, peruse the man we didn't learn about in school for a reason. ",
  },
  {
    id: '5',
    url: 'https://www.google.com',
    image: `${project}manchester-city-logo.svg`,
    title: 'Coming Soon',
    desc: 'A FERN stack homepage for the famous football club.',
  },
  {
    id: '6',
    url: 'https://www.google.com',
    image: `${project}manchester-city-logo.svg`,
    title: 'Coming Soon',
    desc: 'A FERN stack homepage for the famous football club.',
  },
  {
    id: '7',
    url: 'https://www.google.com',
    image: `${project}manchester-city-logo.svg`,
    title: 'Coming Soon',
    desc: 'A FERN stack homepage for the famous football club.',
  },
  {
    id: '8',
    url: 'https://www.google.com',
    image: `${project}manchester-city-logo.svg`,
    title: 'Coming Soon',
    desc: 'A FERN stack homepage for the famous football club.',
  },
  {
    id: '9',
    url: 'https://www.google.com',
    image: `${project}manchester-city-logo.svg`,
    title: 'Coming Soon',
    desc: 'A FERN stack homepage for the famous football club.',
  },
  {
    id: '10',
    url: 'https://www.google.com',
    image: `${project}manchester-city-logo.svg`,
    title: 'Coming Soon',
    desc: 'A FERN stack homepage for the famous football club.',
  },
  {
    id: '11',
    url: 'https://www.google.com',
    image: `${project}manchester-city-logo.svg`,
    title: 'Coming Soon',
    desc: 'A FERN stack homepage for the famous football club.',
  },
  {
    id: '12',
    url: 'https://www.google.com',
    image: `${project}manchester-city-logo.svg`,
    title: 'Coming Soon',
    desc: 'A FERN stack homepage for the famous football club.',
  },
  {
    id: '13',
    url: 'https://www.google.com',
    image: `${project}manchester-city-logo.svg`,
    title: 'Coming Soon',
    desc: 'A FERN stack homepage for the famous football club.',
  },
  {
    id: '17',
    url: 'https://www.google.com',
    image: `${project}manchester-city-logo.svg`,
    title: 'Coming Soon',
    desc: 'A FERN stack homepage for the famous football club.',
  },
  {
    id: '18',
    url: 'https://www.google.com',
    image: `${project}manchester-city-logo.svg`,
    title: 'Coming Soon',
    desc: 'A FERN stack homepage for the famous football club.',
  },
  {
    id: '19',
    url: 'https://www.google.com',
    image: `${project}manchester-city-logo.svg`,
    title: 'Coming Soon',
    desc: 'A FERN stack homepage for the famous football club.',
  },
  {
    id: '20',
    url: 'https://www.google.com',
    image: `${project}manchester-city-logo.svg`,
    title: 'Coming Soon',
    desc: 'A FERN stack homepage for the famous football club.',
  },
  {
    id: '21',
    url: 'https://www.google.com',
    image: `${project}manchester-city-logo.svg`,
    title: 'Coming Soon',
    desc: 'A FERN stack homepage for the famous football club.',
  },
  {
    id: '22',
    url: 'https://www.google.com',
    image: `${project}manchester-city-logo.svg`,
    title: 'Coming Soon',
    desc: 'A FERN stack homepage for the famous football club.',
  },
]

export default projects
